id: P006609
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3508
  title: ཨོ་རྒྱན་པདྨ་འབྱུང་གནས་ཀྱི་གསོལ་འདེབས་ཚན་པ་ཁག་ཅིག
  author: ''
  volumes:
    12b9918082c64bc7a75787bac5687630:
      image_group_id: I1KG3574
      title: ''
      volume_number: 1
      total_pages: 194
