id: P006609
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:10:11.866467
source_metadata:
  id: bdr:W1KG3508
  title: ཨོ་རྒྱན་པདྨ་འབྱུང་གནས་ཀྱི་གསོལ་འདེབས་ཚན་པ་ཁག་ཅིག
  author: ''
  volumes:
    12b9918082c64bc7a75787bac5687630:
      image_group_id: I1KG3574
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
