id: IFF5FB744
legacy_id: P006609
ocr_import_info:
  bdrc_scan_id: W1KG3508
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T16:32:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:07:15.380269+00:00'
last_modified: 2022-08-31 23:07:22.930461
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3508
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3508
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཨོ་རྒྱན་པདྨ་འབྱུང་གནས་ཀྱི་གསོལ་འདེབས་ཚན་པ་ཁག་ཅིག
  author: བྱང་བདག་བཀྲ་ཤིས་སྟོབས་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9621572199219487
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG3574:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3574
      total_pages: 194
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3574.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9621572199219487
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
